site_name: Edra
repo_name: "EdraDocs"
repo_url: https://github.com/edra-unb-fga/EdraDocs
docs_dir: docs

nav:
  - Sobre Nos: 'index.md'
  - Historia da Equipe: 'history.md'
  - Competicoes: 'competitions.md'
  - Projetos: 'projects.md'
  - Patrocinadores: 'sponsors.md'
  - Capacitacoes: 'capabilities.md'
  - Tello: 'tello.md'
  - Padroes de commits: 'commits.md'
  - Membros: 'members.md'

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: img/favicon.png
  favicon: img/Realfavicon.png
  palette:
    - media: "(#5e5e62: light)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "#5e5e62"
      accent: "#5e5e62"
    - media: "(#5e5e62: dark)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: "#5e5e62"
      accent: "#5e5e62"
  font:
    text: Roboto
    code: Roboto Mono



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edra-unb-fga
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/edra-unb
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/edraunb

    


extra_css:
  - stylesheets/extra.css
